"""empty message

Revision ID: 5ccc92b06aa0
Revises: d9dc2b69643f
Create Date: 2016-05-30 11:33:32.201707

"""

# revision identifiers, used by Alembic.
revision = '5ccc92b06aa0'
down_revision = 'd9dc2b69643f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlist', sa.Column('date_modified', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bucketlist', 'date_modified')
    ### end Alembic commands ###
